### ISSUE TITLE
On first run, error

### ISSUE THREAD

**Issue by u9g** [yourfriendoss/Classicube#2]
on first run, i get this error, on the rest everything works

```
(node:111876) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCookieStringSync' of undefined
    at ClassiCube.getServers (C:\Users\---\Documents\git-projs\minecraft-classic-passthrough\node_modules\ClassiCube\index.js:59:26)
    at getServer (C:\Users\---\Documents\git-projs\minecraft-classic-passthrough\index.js:7:24)
    at Object.<anonymous> (C:\Users\---\Documents\git-projs\minecraft-classic-passthrough\index.js:11:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:111876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:111876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by fucksophie** [comment]
cant reproducte

**Comment by u9g** [comment]
remove the classicube.json from your folder where you are running from / now your tmpdir

**Comment by fucksophie** [comment]
still couldn't reproduce
maybe try with the newer version?

**Comment by fucksophie** [comment]
any update?
